/** Missions: player types real kubectl commands; we check live cluster state. */

export const NAMESPACE = 'kubequest';

export const missions = [
  {
    id: 1,
    title: 'Your First Pod',
    xp: 100,
    what: 'A Pod runs one or more containers. It is the smallest deployable unit in Kubernetes.',
    goal: 'Have a Ready pod named beacon running nginx.',
    winHint: 'pod/beacon is Ready',
    starter: [
      'Try creating a pod. Example shape:',
      '  kubectl run beacon --image=nginx:alpine',
      'Then check it:',
      '  kubectl get pods',
    ],
    hints: [
      'kubectl run beacon --image=nginx:alpine',
      'kubectl get pods',
      'kubectl get pod beacon -o wide',
      'kubectl describe pod beacon',
    ],
    winCondition: { type: 'podReady', name: 'beacon' },
  },
  {
    id: 2,
    title: 'Deployments',
    xp: 150,
    what: 'A Deployment keeps N replicas running and restarts them if they die.',
    goal: 'Create deployment/fleet with 2 Ready replicas (nginx).',
    winHint: 'deploy/fleet 2/2 Ready',
    starter: [
      'Create a deployment with 2 replicas. Example:',
      '  kubectl create deployment fleet --image=nginx:alpine --replicas=2',
      'Check:',
      '  kubectl get deploy,pods',
    ],
    hints: [
      'kubectl create deployment fleet --image=nginx:alpine --replicas=2',
      'kubectl get deploy',
      'kubectl get pods -l app=fleet',
      'kubectl describe deploy fleet',
    ],
    winCondition: { type: 'deploymentReady', name: 'fleet', replicas: 2 },
  },
  {
    id: 3,
    title: 'Scale',
    xp: 120,
    what: 'Scaling changes how many pod copies a Deployment runs.',
    goal: 'Scale deployment/fleet to 4 Ready replicas.',
    winHint: 'deploy/fleet 4/4 Ready',
    starter: [
      'Scale the existing fleet deployment:',
      '  kubectl scale deploy/fleet --replicas=4',
      'Check replicas (do not use -w here; it hangs the game):',
      '  kubectl get deploy fleet',
      '  kubectl get pods',
    ],
    hints: [
      'kubectl scale deployment fleet --replicas=4',
      'kubectl get deploy fleet',
      'kubectl get pods',
    ],
    winCondition: { type: 'deploymentReady', name: 'fleet', replicas: 4 },
  },
  {
    id: 4,
    title: 'Services',
    xp: 180,
    what: 'A Service gives pods a stable IP and load-balances across them.',
    goal: 'Expose fleet with a ClusterIP Service named fleet-svc on port 80.',
    winHint: 'svc/fleet-svc exists',
    starter: [
      'Expose the deployment as a ClusterIP service named fleet-svc:',
      '  kubectl expose deploy/fleet --name=fleet-svc --port=80 --target-port=80',
      'Check:',
      '  kubectl get svc',
    ],
    hints: [
      'kubectl expose deployment fleet --name=fleet-svc --port=80 --target-port=80',
      'kubectl get svc fleet-svc',
      'kubectl describe svc fleet-svc',
    ],
    winCondition: { type: 'serviceExists', name: 'fleet-svc' },
  },
  {
    id: 5,
    title: 'ConfigMaps',
    xp: 160,
    what: 'ConfigMaps inject config into pods as env vars or files. Pod specs are immutable — set env at create time, not with set env on a live pod.',
    goal: 'Create configmap quest-config (key MESSAGE) and a Ready pod messenger whose MESSAGE env comes from that configmap.',
    winHint: 'pod/messenger Ready and MESSAGE from cm/quest-config',
    starter: [
      '1) Create the configmap:',
      '  kubectl create configmap quest-config --from-literal=MESSAGE=hello-from-cm',
      '2) Pods cannot change env after creation. Delete a bad messenger if you made one:',
      '  kubectl delete pod messenger --ignore-not-found',
      '3) Create messenger WITH the configmap wired in (sample manifest):',
      '  kubectl apply -f manifests/messenger.yaml',
      '4) Wait until Ready, then prove the env var:',
      '  kubectl get pod messenger',
      '  kubectl exec messenger -- printenv MESSAGE',
      '(The game auto-waits for Ready before exec.)',
    ],
    hints: [
      'kubectl create configmap quest-config --from-literal=MESSAGE=hello-from-cm',
      'kubectl delete pod messenger --ignore-not-found',
      'kubectl apply -f manifests/messenger.yaml',
      'kubectl get pod messenger',
      'kubectl exec messenger -- printenv MESSAGE',
      'Note: kubectl set env works on deploy/... templates, NOT on existing pods.',
    ],
    winCondition: { type: 'podReady', name: 'messenger' },
    extraCheck: 'configMapEnv',
  },
  {
    id: 6,
    title: 'Rolling Update',
    xp: 200,
    what: 'Update a deployment image and Kubernetes rolls out new pods gradually.',
    goal: 'Set deploy/fleet image to nginx:1.27-alpine and have at least one Ready pod.',
    winHint: 'fleet image contains 1.27',
    starter: [
      'Update the container image:',
      '  kubectl set image deploy/fleet nginx=nginx:1.27-alpine',
      'Check rollout (timeout is added automatically in-game):',
      '  kubectl rollout status deploy/fleet',
      '  kubectl get deploy fleet -o jsonpath={.spec.template.spec.containers[0].image}',
    ],
    hints: [
      'kubectl set image deployment/fleet nginx=nginx:1.27-alpine',
      'kubectl rollout status deployment/fleet',
      'kubectl get pods',
      'Container name is nginx (from the original image name).',
    ],
    winCondition: { type: 'deploymentImage', name: 'fleet', imageContains: '1.27' },
  },
  {
    id: 7,
    title: 'Health Probes',
    xp: 220,
    what: 'Readiness and liveness probes tell Kubernetes if a container is OK.',
    goal: 'Create deployment healthy-app (2 replicas, nginx) with HTTP readiness AND liveness probes on path / port 80.',
    winHint: 'deploy/healthy-app 2/2 Ready with probes',
    starter: [
      'Easiest with a manifest file. Create one, then apply it:',
      '  kubectl apply -f manifests/healthy-app.yaml',
      '(That file is in this repo. Open it, read the probes, then apply.)',
      'Or write your own YAML and apply -f ./my.yaml',
    ],
    hints: [
      'kubectl apply -f manifests/healthy-app.yaml',
      'kubectl get deploy healthy-app',
      'kubectl describe deploy healthy-app',
    ],
    winCondition: { type: 'deploymentReady', name: 'healthy-app', replicas: 2 },
    extraCheck: 'hasProbes',
    probeDeploy: 'healthy-app',
  },
  {
    id: 8,
    title: 'Resources',
    xp: 250,
    what: 'requests help scheduling; limits cap CPU/memory usage.',
    goal: 'Create deployment bounded-app (1 replica, nginx) with CPU/memory requests AND limits set.',
    winHint: 'deploy/bounded-app 1/1 Ready with resources',
    starter: [
      'Apply the sample manifest:',
      '  kubectl apply -f manifests/bounded-app.yaml',
      'Inspect resources:',
      '  kubectl describe deploy bounded-app',
    ],
    hints: [
      'kubectl apply -f manifests/bounded-app.yaml',
      'kubectl get deploy bounded-app',
      'kubectl get pod -l app=bounded-app -o jsonpath="{.items[0].spec.containers[0].resources}"',
    ],
    winCondition: { type: 'deploymentReady', name: 'bounded-app', replicas: 1 },
    extraCheck: 'hasResources',
    resourceDeploy: 'bounded-app',
  },
];

export function getMission(id) {
  return missions.find((m) => m.id === Number(id));
}

// Complex / real-world telemetry arc
missions.push(
  {
    id: 9,
    title: 'Observability Stack',
    xp: 300,
    track: 'telemetry',
    what: 'Real platforms ship metrics and traces through an OpenTelemetry Collector to backends like Jaeger and Prometheus.',
    goal: 'Deploy Jaeger, the OTel Collector, and Prometheus in kubequest (all Ready).',
    winHint: 'deploy/jaeger, otel-collector, prometheus are Ready',
    starter: [
      'Build is already done in Codespaces/CI. Locally run: npm run build:telemetry',
      'Apply the stack (order matters for readiness, but one shot is fine):',
      '  kubectl apply -f manifests/telemetry/jaeger.yaml',
      '  kubectl apply -f manifests/telemetry/otel-collector-config.yaml',
      '  kubectl apply -f manifests/telemetry/otel-collector.yaml',
      '  kubectl apply -f manifests/telemetry/prometheus.yaml',
      '  kubectl get deploy -l kq.stack=telemetry',
      'Open the live UI: http://localhost:3847',
    ],
    hints: [
      'kubectl apply -f manifests/telemetry/jaeger.yaml',
      'kubectl apply -f manifests/telemetry/otel-collector-config.yaml',
      'kubectl apply -f manifests/telemetry/otel-collector.yaml',
      'kubectl apply -f manifests/telemetry/prometheus.yaml',
      'kubectl get pods -l kq.stack=telemetry',
      'kubectl describe deploy otel-collector',
    ],
    winCondition: { type: 'deploymentReady', name: 'jaeger', replicas: 1 },
    extraCheck: 'telemetryStack',
    stackDeployments: ['jaeger', 'otel-collector', 'prometheus'],
  },
  {
    id: 10,
    title: 'Instrumented Service',
    xp: 300,
    track: 'telemetry',
    what: 'Apps export OTLP to the collector. Our telemetry-api image embeds the OpenTelemetry Node SDK.',
    goal: 'Deploy telemetry-api (2 Ready replicas) configured to send OTLP to otel-collector:4318.',
    winHint: 'deploy/telemetry-api 2/2 Ready',
    starter: [
      'Load the local image into kind if you have not:',
      '  npm run build:telemetry',
      'Deploy the API:',
      '  kubectl apply -f manifests/telemetry/telemetry-api.yaml',
      '  kubectl get deploy telemetry-api',
      'Watch pods appear in the dashboard Cluster tab.',
    ],
    hints: [
      'npm run build:telemetry',
      'kubectl apply -f manifests/telemetry/telemetry-api.yaml',
      'kubectl get pods -l app=telemetry-api',
      'kubectl logs deploy/telemetry-api',
    ],
    winCondition: { type: 'deploymentReady', name: 'telemetry-api', replicas: 2 },
  },
  {
    id: 11,
    title: 'Live Traces',
    xp: 350,
    track: 'telemetry',
    what: 'Traffic creates distributed traces. Jaeger stores them; the KubeQuest UI tails the Jaeger query API live.',
    goal: 'Generate traffic so Jaeger has traces for service telemetry-api.',
    winHint: 'jaeger has traces for telemetry-api',
    starter: [
      'Send requests through the service (in-cluster DNS):',
      '  kubectl run hit --rm -i --restart=Never --image=curlimages/curl:8.5.0 -- \\',
      '    curl -sf http://telemetry-api:8080/api/hello',
      'Repeat a few times, wait ~10s for export, then:',
      '  check',
      'Or use the dashboard Traces tab / Generate traffic button.',
    ],
    hints: [
      'kubectl run hit --rm -i --restart=Never --image=curlimages/curl:8.5.0 -- curl -sf http://telemetry-api:8080/api/hello',
      'kubectl run hit2 --rm -i --restart=Never --image=curlimages/curl:8.5.0 -- curl -sf http://telemetry-api:8080/api/boom',
      'Open http://localhost:3847 → Traces',
      'kubectl logs deploy/otel-collector --tail=20',
    ],
    winCondition: { type: 'deploymentReady', name: 'telemetry-api', replicas: 1 },
    extraCheck: 'jaegerHasTraces',
    traceService: 'telemetry-api',
  },
  {
    id: 12,
    title: 'Live Metrics',
    xp: 350,
    track: 'telemetry',
    what: 'Custom metrics (kq_http_requests_total) flow OTLP → collector → Prometheus scrape endpoint.',
    goal: 'Prometheus has series for kq_http_requests_total.',
    winHint: 'prometheus query kq_http_requests_total returns series',
    starter: [
      'Generate more traffic if needed, wait for scrape (5s interval), then check.',
      'Dashboard Metrics tab charts this live.',
      'PromQL:',
      '  kq_http_requests_total',
    ],
    hints: [
      'kubectl run hit3 --rm -i --restart=Never --image=curlimages/curl:8.5.0 -- curl -sf http://telemetry-api:8080/api/hello',
      'Open http://localhost:3847 → Metrics',
      'kubectl port-forward svc/prometheus 9090:9090',
    ],
    winCondition: { type: 'deploymentReady', name: 'prometheus', replicas: 1 },
    extraCheck: 'prometheusMetric',
    promQuery: 'kq_http_requests_total',
  }
);
