apiVersion: v1
kind: Service
metadata:
  name: telemetry-api
  namespace: kubequest
  labels:
    app: telemetry-api
    kq.stack: telemetry
spec:
  selector:
    app: telemetry-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api
  namespace: kubequest
  labels:
    app: telemetry-api
    kq.stack: telemetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
        kq.stack: telemetry
    spec:
      containers:
        - name: api
          image: kubequest-telemetry-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: OTEL_SERVICE_NAME
              value: telemetry-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
